const portfolio = {
    introText:{ 
        color:'',
        opacity:0,
        fontFamily:'',
        FontWeight:'',
        fontSize:'',
        letterSpacing:0,
        wordSpacing:0,
        lineHeight:0,
        textAlign:'',
        textTransform:'',
        textDecoration:''

    },
    aboutMe:{
        color:'',
        opacity:0,
        fontFamily:'',
        FontWeight:'',
        fontSize:'',
        letterSpacing:0,
        wordSpacing:0,
        lineHeight:0,
        textAlign:'',
        textTransform:'',
        textDecoration:''
    },
    button:{ 
        color:'',
        opacity:0,
        fontFamily:'',
        FontWeight:'',
        fontSize:'',
        letterSpacing:0,
        wordSpacing:0,
        lineHeight:0,
        textAlign:'',
        textTransform:'',
        textDecoration:'',
        borderRadius:'',
        padding:'',
        backgroundColor:'',
        
    }, 
    image:'',
    work:[
        {
            description:'',
            title:'',
            url:'',
            imageUrl:''
        }
    ],
    skills:[
        ''
    ],
    socialLinks:[
        {
            title:'',
            url:''
        }
    ],
    resume:'',
    userId:''
}